### ISSUE TITLE
bootstrap.sh Syntax error

### ISSUE THREAD

**Issue by tdannecy** [cf020031308/pomodoro-warriors#2]
Running this in a FreeBSD jail and I'm receiving this error when running bootstrap.sh
`bootstrap.sh: 3: Syntax error: "(" unexpected`

**Comment by xpat** [comment]
same exact error here, running on Ubuntu 16.04

**Comment by cf020031308** [comment]
I'm sorry for the inconvenience. This script is only tested on my Mac so it may not be compatible in your situation.
I have considered to rewrite it with pure python to solve this issue. But currently I'm over head and ears in preparing for an exam to a further study so I'm afraid the changes would not be made in the following few months, but would after.

**Comment by Michael-Jing** [comment]
I managed to get rid of this error by editing the script myself, However, the app is not working since there is a hardcoded path in the code. Could please look into the issue?
